#!/bin/bash
set -e
cd "$( dirname "${BASH_SOURCE[0]}" )/.."

target=./coverage.txt
tmp=/tmp/robotstxt-coverage-one.txt
flags=(
  -covermode=atomic "-coverprofile=$tmp"
  -race
)

rm -f "$target"
for d in $(go list ./... |fgrep -v vendor) ; do
  go test ${flags[@]} $d
  [[ -r "$tmp" ]] && cat $tmp >>"$target"
done
rm -f "$tmp"
